USE MASTER
GO

CREATE DATABASE ProjectLima
GO

USE ProjectLima
GO

CREATE TABLE Board(
	Id int IDENTITY (1,1) NOT NULL,
	PRIMARY KEY (Id)
)

CREATE TABLE Spalte(
	Id int IDENTITY(1,1) NOT NULL,
	Titel NVARCHAR(100) NOT NULL,
	PRIMARY KEY (Id),
	BoardId int FOREIGN KEY REFERENCES Board(Id)
)

CREATE TABLE Karte(
	Id int IDENTITY(1,1) NOT NULL,
	Titel NVARCHAR(100) NOT NULL,
	Beschreibung NVARCHAR(MAX) NULL,
	SpalteId int FOREIGN KEY REFERENCES Spalte(Id)
)
GO